<?php 

/**
 * @file
 * fjm_turina customizations
 */
 
 /**
  * Implementation of hook_menu
  */
function fjm_turina_menu() {
  
  $items = array();
  $items['home'] = array(
    'title' => 'Home',
    'page callback' => 'fjm_turina_landing_page',
    'access arguments' => array('access content'),
    'file' => 'fjm_turina_landing.page.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['names'] = array(
    'title' => 'Names',
    'page callback' => 'fjm_turina_names',
    'access arguments' => array('access content'),
    'file' => 'fjm_turina_names.page.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['subjects'] = array(
    'title' => 'Subjects',
    'page callback' => 'fjm_turina_subjects',
    'access arguments' => array('access content'),
    'file' => 'fjm_turina_names.page.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['genres'] = array(
    'title' => 'Genres',
    'page callback' => 'fjm_turina_genres',
    'access arguments' => array('access content'),
    'file' => 'fjm_turina_names.page.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['titles'] = array(
    'title' => 'Titles',
    'page callback' => 'fjm_turina_titles',
    'access arguments' => array('access content'),
    'file' => 'fjm_turina_names.page.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['turina_batch'] = array(
    'title' => 'Batch ingest',
    'page callback' => 'fjm_turina_batch_ingest',
    'access arguments' => array('ingest new fedora objects'),
    'file' => 'fjm_turina.batch.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['turina_batch_results'] = array(
    'title' => 'Batch results',
    'page callback' => 'fjm_turina_batch_result',
    'access arguments' => array('ingest new fedora objects'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  return $items;
}

function fjm_turina_batch_result($filename = 'ingest-results.dat') {
  dsm(unserialize(file_get_contents(file_directory_path() . '/' . $filename)));
  return TRUE;
}

/**
 * Implementation of hook_theme
 */
function fjm_turina_theme($existing, $type, $theme, $path) {
  $templates_path = drupal_get_path('module', 'fjm_turina') . '/templates';
  return array(
    'fjm_turina_landing' => array(
      'path' => $templates_path,
      'arguments' => array(
        'bio' => NULL,
        'content' => NULL,
        'collections' => NULL,
        'browse' => NULL,
        'search' => NULL,
      ),
      'template' => 'fjm_turina_landing_page',
    ),
    'fjm_turina_landing_collections' => array(
      'arguments' => array(
        'music' => NULL,
        'personal_archive' => NULL,
      ),
    ),
    'fjm_turina_book_description' => array(
      'arguments' => array(
        'pid' => NULL,
      ), 
      'path' => $templates_path,
      'template' => 'fjm-turina-book-desc',
    ),
    'turina_letterer' => array(
      'arguments' => array(
        'queries' => array(),
        'map' => array(),
        'selected' => 'ALL',
        'path' => 'names',
      ),
      'path' => $templates_path,
      'template' => 'fjm-turina-name-letterer',
    ),
    'turina_facet_list' => array(
      'arguments' => array(
        'names' => array(),
        'field' => 'mods_name_primary_personal_ms',
      ),
      'path' => $templates_path,
      'template' => 'fjm-turina-name-list',
    ),
  );
}

function template_preprocess_fjm_turina_book_description(&$vars) {
  module_load_include('inc', 'fedora_repository', 'api/fedora_item');
  $pid = $vars['pid'];
  $item = new Fedora_Item($pid);
  if ($pid === NULL) {
    //PID is null!?  What is there to theme...
  }
  elseif (!$item->exists()) {
    //The item doesn't exists...  What to do?
  }
  
  $mods_str = $item->get_datastream_dissemination('MODS');
  $mods_doc = new DOMDocument();
  $mods_doc->loadXML($mods_str);
  
  $mods_xpath = new DOMXPath($mods_doc);
  $mods_xpath->registerNamespace('mods', 'http://www.loc.gov/mods/v3');
  
  $vars['title'] = $mods_xpath->evaluate('string(/mods:mods/mods:titleInfo/mods:title/text())');
  $vars['description'] = $mods_xpath->evaluate('string(/mods:mods/mods:abstract/text())');

  $vars['desc_list'] = array(
    array(
      'label' => t('Genre'),
      'value' => $mods_xpath->evaluate('string(/mods:mods/mods:genre/text())'),
    ),
    array(
      'label' => t('Date'),
      'value' => $mods_xpath->evaluate('string(/mods:mods/mods:originInfo/mods:dateCreated[not(@encoding)]/text())'),
    ),
    array(
      'label' => t('Topic'),
      'value' => $mods_xpath->evaluate('string(/mods:mods/mods:subject/mods:topic/text())'),
    ), 
    array(
      'label' => t('Physical Description'),
      'value' => $mods_xpath->evaluate('string(/mods:mods/mods:physicalDescription/mods:form[@authority="marcform"]/text())')
    ),
    array(
      'label' => t('General Note'),
      'value' => $mods_xpath->evaluate('string(/mods:mods/mods:note/text())'),
    ),
  );
  
  if (array_key_exists('PDF', $item->get_datastreams_list_as_array())) {
    $vars['pdf_url'] = url("fedora/repository/object_download/$pid/PDF");
  }
  
  global $base_url;
  $viewer_path = drupal_get_path('module', 'islandora_bookviewer');
  $vars['fullview_url'] = url("$base_url/$viewer_path/mainpage.php", array(
    'query' => array(
      'pid' => $pid,
    ),
    'fragment' => 'page/1/mode/1up',
    'absolute' => TRUE,
  ));
  
  module_load_include('inc', 'fedora_repository', 'ObjectHelper');
  $images = ObjectHelper::performSparqlQuery(<<<END_QUERY
PREFIX ip: <info:islandora/islandora-system:def/pageinfo#>
SELECT ?page ?pageNumber
FROM <#ri>
WHERE {
  ?page ip:isPageOf <info:fedora/$pid> ;
        ip:isPageNumber ?pageNumber .
}
ORDER BY ?pageNumber
LIMIT 1
END_QUERY
);
  
  if (count($images) > 0) {
    $vars['image_url'] = url("fedora/repository/{$images[0]['page']}/WEB_JPG");
  }
}

/**
 * Collection links theme function
 */

function theme_fjm_turina_landing_collections($music, $personal_archive) {
  $output = '<h3 class="front-title">' . t('Music') . '</h3>';
  $output .= theme('links', $music, array('class' => 'fjm-turina-links-music'));
  $output .= '<h3 class="front-title">' . t('Personal Archive') . '</h3>';
  $output .= theme('links', $personal_archive, array('class' => 'fjm-turina-links-personal-archive'));

  return $output;  
}

function fjm_turina_fjm_turina_pre_ingest_alter(&$object) {
  module_load_include('inc', 'fjm_turina', 'ingest-help');

  _fjm_turina_add_derivatives($object);
}

function fjm_turina_fjm_turina_post_ingest_alter(&$object) {
  module_load_include('inc', 'fjm_turina', 'ingest-help');

  _fjm_turina_delete_derived_files($object);
}

function fjm_turina_islandora_bookviewer_get_page($pid) {
  $url = url("fedora/repository/$pid/WEB_JPG", array('absolute' => TRUE));

  return array(
    'fjm_turina' => array(
      '#url' => $url,
      '#weight' => -5,
    ),
  );
}

/**
 * Implementation of hook_islandora_tabs().
 */
function fjm_turina_islandora_tabs($content_models, $pid, $page) {
  module_load_include('inc', 'fedora_repository', 'ObjectHelper');
  $cmodel_query = <<<END_QUERY
PREFIX fm: <info:fedora/fedora-system:def/model#>
SELECT ?model
FROM <#ri>
WHERE {
  <info:fedora/$pid> fm:hasModel ?model .
}
END_QUERY;
  
  $cmodels = ObjectHelper::performSparqlQuery($cmodel_query);
  
  $tabset = array();
  foreach ($cmodels as $cmodel) {
    if ($cmodel['model'] == 'jt:bookCModel') {
      $tabset['turina-book'] = array(
        '#type' => 'tabpage',
        '#title' => t('Content'),
        '#tab_name' => 'turina-book',
        '#content' => theme('fjm_turina_book_description', $pid),
      );
    }
  }
  return $tabset;
}

function fjm_turina_required_fedora_objects() {
  return array(
    'fjm_turina' => array(
      'module' => 'fjm_turina',
      'title' => t('FJM Turina Objects'),
      'objects' => array(
        array(
          'pid' => 'jt:bookCollection',
          'label' => 'Legado Joaquín Turina',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'islandora:root',
        ),
      ),
    ),
  );
}
